language: java
jdk:
  - oraclejdk8
scripts:
	- mvn test -B
	- screen mvn clean package jetty:run
	- curl -d '{"username":"Bob","firstName":"Bob","lastName":"Demo","email":"bobdemo@gmail.com","createTime":"2017-07-21T17:32:28Z","updateTime":"2017-07-21T17:32:28Z","description":"Test account for Bob", "password":"PASSWORD"}' -H "Content-Type: application/json" -X POST http://localhost:8080/v1/accounts/
	- curl http://localhost:8080/v1/accounts/Alice
	- curl http://localhost:8080/v1/accounts/Bob
