language: java
jdk:
  - oraclejdk8
script:
  - mvn test -B
  - mvn clean package jetty:run &
  # sleep to wait for jetty service to be ready
  - sleep 30
  # directly write curl in .yml will lead to parsing problem
  - bash .testscript.sh